services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

volumes:
  redis:
  redis-config:
  postgres-data: